version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"

    # Apply default reviewer and label to created
    # pull requests
    default_reviewers:
      - "github-username"
    default_labels:
      - "label-name"
